### ISSUE TITLE
Payment screen

### ISSUE THREAD

**Issue by gimpdaddy** [acidsploit/react-pos#1]
1. "Fetching Exchange Rate..." before loading the number pad can be slow to load and slows down the experience. Could the number pad load first and have confirmation of the exchange rate in the background/show a status elsewhere on screen as opposed to holding up the entire page?

2. Occasionally when using the payment screen there appears to be a scenario where the exchange rate is loaded a second time and refreshes the screen and number pad. Sequence of events:
- Click payment screen
- Payment screen loads and fetches exchange rate
- Enter payment value
- Payment screen reloads unexpectedly
- Need to re-enter payment value

3. On small screens the currency toggle button confirmation is a nuisance, especially when toggling quickly, as the confirmations stack up ("toggle currency" and "exchange rate fetched"). This can easily occupy half the screen of a mobile device. Perhaps only one confirmation is required ("Active Currency now 1 BCH:1000 USD")? Also multiple confirmations could replace the preceding confirmation as opposed to continuously stacking?

4. A confirmation sound when a payment is received/verified?

**Comment by gimpdaddy** [comment]
4. When a payment is received a confirmation sound may be good addition

**Comment by acidsploit** [comment]
1. I'll have to look into that, but I think it's best to have the most current exchange rate loaded before starting an order or payment.

2. Indeed, that is a bug. I forgot to prevent some default events. Will be fixed asap.

3. I don't think you'll be tapping that button in quick succession in a real life scenario. I have to see if I can find a way to make the notification less obtrusive on small screens.

4. Great idea!

**Comment by acidsploit** [comment]
Issue 2 is fixed with commit https://github.com/acidsploit/react-pos/commit/24f1d366a25158e3f92609f31b052627ad664f03
